services:
  mysql:
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - ${MYSQL_PORT}
    volumes:
      - mysql_data:/var/lib/mysql

  redis:      #todo 운영 서버에서는 비밀번호, bind 0.0.0.0, replication(선택) 반드시 설정
    image: redis:7.2
    ports:
      - ${REDIS_PORT}
#    command:
#      - redis-server --requirepass ${REDIS_PASSWORD}

# https://stackoverflow.com/questions/73385880/mockoon-docker-compose-error-missing-required-flag/73386024#73386024
  mock-server:
    image: mockoon/cli:latest
    command: ["--data", "/data/franchise-api.json", "--port", "3000", "--hostname", "0.0.0.0"]
    ports:
      - ${MOCKOON_PORT}
    volumes:
      - ./mockoon/franchise-api.json:/data/franchise-api.json:ro

volumes:
  mysql_data:

