services:
  mysql:
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - ${MYSQL_PORT}
    volumes:
      - mysql_data:/var/lib/mysql

  redis:      #todo 운영 서버에서는 비밀번호, bind 0.0.0.0, replication(선택) 반드시 설정
    image: redis:7.2
    ports:
      - ${REDIS_PORT}
#    command:
#      - redis-server --requirepass ${REDIS_PASSWORD}

volumes:
  mysql_data: