spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/groupware_test
    username: groupware
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: never

  docker:
    compose:
      lifecycle-management: none